# Generated by Django 3.1 on 2020-08-23 21:05

from django.db import migrations


def fill_models(apps, schema_editor):
    clients = [
        (0, ">_<"),
        (1, "O_O"),
        (2, ">_>"),
        (3, ";_;"),
    ]    
    areas = [
        (0, "Conquest"),
        (1, "War"),
        (2, "Famine"),
        (3, "Plague"),
    ]
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Client = apps.get_model('polls','Client')
    Area = apps.get_model('polls','ProductArea')
    for item_ in clients:
        c = Client(client_text = item_[1])
        c.save()
    for item_ in areas:
        a = Area(prod_area_text = item_[1])
        a.save()


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(fill_models),
    ]
